services:
  server:
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - ./test.nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - .:/var/www:ro
  php:
    image: php:fpm-alpine
    working_dir: /var/www
    volumes:
      - .:/var/www:delegated
  composer:
    image: composer:latest
    working_dir: /app
    entrypoint:
      - composer
    volumes:
      - .:/app:rw
